apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlc-player-ds
  namespace: default
  labels:
    app: vlc-player
    phase: daemonset
    version: v1.0.0
spec:
  selector:
    matchLabels:
      app: vlc-player
      phase: daemonset
  template:
    metadata:
      labels:
        app: vlc-player
        phase: daemonset
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      # Node Selection
      nodeSelector:
        kubernetes.io/os: linux
      
      # Tolerations for special nodes
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
        
      # Security Context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        
      containers:
      - name: vlc-player
        image: vlc-player:latest
        imagePullPolicy: IfNotPresent
        
        # Container Ports
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
          
        # Environment Variables
        env:
        - name: VLC_PORT
          value: "8080"
        - name: VLC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vlc-player-secret
              key: http-password
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: vlc-player-secret
              key: license-key
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
              
        # Resource Limits and Requests
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
            ephemeral-storage: "2Gi"
          requests:
            cpu: "250m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
            
        # Volume Mounts
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: playlist-volume
          mountPath: /app/playlists
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
        - name: tmp-volume
          mountPath: /tmp
          
        # Liveness Probe
        livenessProbe:
          httpGet:
            path: /requests/status.xml
            port: 8080
            scheme: HTTP
            httpHeaders:
            - name: Authorization
              value: Basic OnZsY3Bhc3N3b3JkMTIz  # :vlcpassword123
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          
        # Readiness Probe
        readinessProbe:
          httpGet:
            path: /requests/status.xml
            port: 8080
            scheme: HTTP
            httpHeaders:
            - name: Authorization
              value: Basic OnZsY3Bhc3N3b3JkMTIz  # :vlcpassword123
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          
        # Startup Probe
        startupProbe:
          httpGet:
            path: /requests/status.xml
            port: 8080
            scheme: HTTP
            httpHeaders:
            - name: Authorization
              value: Basic OnZsY3Bhc3N3b3JkMTIz  # :vlcpassword123
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
          successThreshold: 1
          
        # Security Context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
            
      # Volumes
      volumes:
      - name: config-volume
        configMap:
          name: vlc-player-config
          items:
          - key: vlc.conf
            path: vlc.conf
          - key: env.conf
            path: env.conf
          - key: logging.conf
            path: logging.conf
      - name: playlist-volume
        configMap:
          name: vlc-player-config
          items:
          - key: playlist.m3u
            path: playlist.m3u
      - name: logs-volume
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 500Mi
          
      # DNS Policy
      dnsPolicy: ClusterFirst
      
      # Restart Policy
      restartPolicy: Always
      
      # Termination Grace Period
      terminationGracePeriodSeconds: 30
      
  # Update Strategy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1