apiVersion: v1
kind: Namespace
metadata:
  name: vlc-system
  labels:
    app: vlc-operator
    control-plane: vlc-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vlc-operator
  namespace: vlc-system
  labels:
    app: vlc-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vlc-operator
  labels:
    app: vlc-operator
rules:
# VLC Player CRD permissions
- apiGroups: ["media.example.com"]
  resources: ["vlcplayers", "vlcplaylists"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["media.example.com"]
  resources: ["vlcplayers/status", "vlcplaylists/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["media.example.com"]
  resources: ["vlcplayers/finalizers", "vlcplaylists/finalizers"]
  verbs: ["update"]

# Core Kubernetes resources
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

# Apps resources
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Autoscaling resources
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["verticalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Policy resources
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Metrics
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

# Events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vlc-operator
  labels:
    app: vlc-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vlc-operator
subjects:
- kind: ServiceAccount
  name: vlc-operator
  namespace: vlc-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vlc-operator-leader-election
  namespace: vlc-system
  labels:
    app: vlc-operator
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vlc-operator-leader-election
  namespace: vlc-system
  labels:
    app: vlc-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vlc-operator-leader-election
subjects:
- kind: ServiceAccount
  name: vlc-operator
  namespace: vlc-system