apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vlcplayers.media.example.com
  labels:
    app: vlc-operator
    phase: operators
spec:
  group: media.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                maximum: 20
                default: 3
              version:
                type: string
                default: "3.0.18"
                pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
              platform:
                type: string
                enum: ["linux", "windows"]
                default: "linux"
              image:
                type: object
                properties:
                  repository:
                    type: string
                    default: "vlc-player"
                  tag:
                    type: string
                  pullPolicy:
                    type: string
                    enum: ["Always", "IfNotPresent", "Never"]
                    default: "IfNotPresent"
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "1000m"
                      memory:
                        type: string
                        default: "1Gi"
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "250m"
                      memory:
                        type: string
                        default: "256Mi"
              storage:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  size:
                    type: string
                    default: "10Gi"
                  storageClass:
                    type: string
                    default: "standard"
                  accessMode:
                    type: string
                    enum: ["ReadWriteOnce", "ReadOnlyMany", "ReadWriteMany"]
                    default: "ReadWriteOnce"
              autoscaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  minReplicas:
                    type: integer
                    minimum: 1
                    default: 2
                  maxReplicas:
                    type: integer
                    maximum: 50
                    default: 10
                  targetCPUUtilization:
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 70
                  targetMemoryUtilization:
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 80
              networking:
                type: object
                properties:
                  serviceType:
                    type: string
                    enum: ["ClusterIP", "NodePort", "LoadBalancer"]
                    default: "LoadBalancer"
                  port:
                    type: integer
                    minimum: 1
                    maximum: 65535
                    default: 8080
              security:
                type: object
                properties:
                  runAsNonRoot:
                    type: boolean
                    default: true
                  runAsUser:
                    type: integer
                    default: 1000
                  fsGroup:
                    type: integer
                    default: 1000
              updateStrategy:
                type: object
                properties:
                  type:
                    type: string
                    enum: ["RollingUpdate", "Recreate"]
                    default: "RollingUpdate"
                  rollingUpdate:
                    type: object
                    properties:
                      maxUnavailable:
                        anyOf:
                        - type: integer
                        - type: string
                        default: 1
                      maxSurge:
                        anyOf:
                        - type: integer
                        - type: string
                        default: 1
            required:
            - replicas
            - platform
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed", "Succeeded"]
              replicas:
                type: integer
              readyReplicas:
                type: integer
              updatedReplicas:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
                  required:
                  - type
                  - status
    subresources:
      status: {}
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
        labelSelectorPath: .status.selector
    additionalPrinterColumns:
    - name: Replicas
      type: integer
      jsonPath: .spec.replicas
    - name: Ready
      type: integer
      jsonPath: .status.readyReplicas
    - name: Platform
      type: string
      jsonPath: .spec.platform
    - name: Version
      type: string
      jsonPath: .spec.version
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: vlcplayers
    singular: vlcplayer
    kind: VLCPlayer
    shortNames:
    - vlcp