apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vlcplaylists.media.example.com
  labels:
    app: vlc-operator
    phase: operators
spec:
  group: media.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                minLength: 1
                maxLength: 63
              description:
                type: string
                maxLength: 255
              items:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      minLength: 1
                    url:
                      type: string
                      pattern: '^https?://.*'
                    duration:
                      type: string
                      pattern: '^[0-9]+:[0-9]{2}:[0-9]{2}$'
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                  required:
                  - title
                  - url
              autoPlay:
                type: boolean
                default: true
              loop:
                type: boolean
                default: false
              shuffle:
                type: boolean
                default: false
              schedule:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  cron:
                    type: string
                    pattern: '^(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5,7})$'
                  timezone:
                    type: string
                    default: "UTC"
            required:
            - name
            - items
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Active", "Failed"]
              itemCount:
                type: integer
              lastUpdated:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
                  required:
                  - type
                  - status
    additionalPrinterColumns:
    - name: Items
      type: integer
      jsonPath: .status.itemCount
    - name: AutoPlay
      type: boolean
      jsonPath: .spec.autoPlay
    - name: Loop
      type: boolean
      jsonPath: .spec.loop
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: vlcplaylists
    singular: vlcplaylist
    kind: VLCPlaylist
    shortNames:
    - vlcpl