apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vlc-player-vpa
  namespace: default
  labels:
    app: vlc-player
    phase: statefulset
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vlc-player-sts
  updatePolicy:
    updateMode: "Auto"  # Options: "Off", "Initial", "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: vlc-player
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 4000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
    - containerName: media-downloader
      mode: "Off"  # Don't auto-scale init containers

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vlc-player-pdb
  namespace: default
  labels:
    app: vlc-player
    phase: statefulset
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vlc-player
      phase: statefulset